title: Offz's site
tagline: Welcome!
description: >-
  Offz's site for things

timezone: America/Toronto

github:
  username: 0ffz

social:
  name: Daniel Voznyy
  email: dan.voznyy@gmail.com
  links:
    - https://github.com/0ffz

avatar: https://www.gravatar.com/avatar/7af819b50328377573baae500caa6e0d?size=400

theme: jekyll-theme-chirpy